version: '2'
services:
  redis:
    image: redis
    restart: always
  sinatra-post-to-redis:
    image: onlyofficeqa/sinatra-post-to-redis
    ports:
      - '8008:80'
    links:
      - redis
    restart: always
  redis-to-telegram:
    tty: true
    build: .
    links:
      - redis
    restart: always
