version: '2'
services:
  redis:
    image: redis
    restart: always
  sinatra-post-to-redis:
    build: https://github.com/onlyoffice-testing-robot/sinatra-post-to-redis.git
    ports:
      - '8008:80'
    links:
      - redis
    restart: always
  redis-to-telegram:
    tty: true
    build: .
    links:
      - redis
    restart: always
